In [7]:
import numpy as np

test_a = np.array([[1,2,3],[4,5,6]], float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [6]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [10]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
test_b = np.arange(7,13).reshape(3,2)
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [12]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [13]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [17]:
test_matrix = np.array([[1,2,3], [4,5,6]], float)
scala = 3
test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
test_matrix + scala

array([[4., 5., 6.],
       [7., 8., 9.]])

In [19]:
test_matrix - scala

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [20]:
test_matrix * scala

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [21]:
test_matrix / scala

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [22]:
test_matrix // scala

array([[0., 0., 1.],
       [1., 1., 2.]])

In [23]:
test_matrix ** scala

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [24]:
test_matrix = np.arange(1,13).reshape(4,3)
test_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
test_vector = np.arange(10,40,10)
test_vector

array([10, 20, 30])

In [1]:
test_matrix + test_vector

NameError: name 'test_matrix' is not defined

In [2]:
def sclar_vertor_product(scalar, vertor):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iternation_max = 10000000

scalar = 2
vector = list(range(iternation_max))


In [3]:
%timeit sclar_vertor_product(scalar, vector)

897 ms ± 18.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit [ scalar * value for value in range(iternation_max)]

894 ms ± 27.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit np.arange(iternation_max) * scalar

32.8 ms ± 692 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
