In [2]:
import numpy as np

test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array >3

array([False,  True, False, False, False,  True,  True,  True])

In [5]:
test_array[test_array>3]

array([4., 8., 9., 7.])

In [8]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [9]:
A = np.array([11,3,4,5,6])
A


array([11,  3,  4,  5,  6])

In [11]:
B = A < 5
B

array([False,  True,  True, False, False])

In [12]:
B.astype(np.int)

array([0, 1, 1, 0, 0])

In [13]:
a = np.array([2,4,6,8], float)
a

array([2., 4., 6., 8.])

In [14]:
b = np.array([0,0,1,2,1], int)
b

array([0, 0, 1, 2, 1])

In [15]:
a[b]

array([2., 2., 4., 6., 4.])

In [16]:
a.take(b)

array([2., 2., 4., 6., 4.])

In [3]:
a = np.array([[1,4],[9,16]], float)
a

array([[ 1.,  4.],
       [ 9., 16.]])

In [0]:
b = np.array([0,0,1,1,0], float)
a