In [2]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.any(a>5), np.any(a<0)

(True, False)

In [4]:
np.all(a>5), np.all(a<10)

(False, True)

In [6]:
test_a = np.array([1,3,0], float)
test_a

array([1., 3., 0.])

In [7]:
test_b = np.array([5,2,1], float)
test_b

array([5., 2., 1.])

In [8]:
test_a > test_b

array([False,  True, False])

In [10]:
(test_a > test_b).any()

True

In [12]:
a = np.array([1,3,0], float)
a

array([1., 3., 0.])

In [13]:
np.logical_and( a>0, a<3)

array([ True, False, False])

In [15]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [17]:
c = np.array([False, True, False], bool)
c

array([False,  True, False])

In [18]:
np.logical_or(b,c)

array([ True,  True,  True])

In [19]:
np.where(a>0, 3,2)

array([3, 3, 2])

In [20]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.where(a>5)

(array([6, 7, 8, 9]),)

In [25]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [27]:
np.isnan(a)

array([False,  True, False])

In [28]:
np.isfinite(a)

array([ True, False, False])

In [29]:
a = np.array([1,2,3,4,5,8,78,23,3])
a

array([ 1,  2,  3,  4,  5,  8, 78, 23,  3])

In [30]:
np.argmax(a), np.argmin(a)

(6, 0)

In [32]:
a = np.array( [[1,2,4,5],[9,88,6,45],[9,76,3,4]])
a

array([[ 1,  2,  4,  5],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [33]:
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))