In [1]:
import numpy as np

In [2]:
aa = np.array([0,0,1,1,0], float)
aa


array([0., 0., 1., 1., 0.])

In [4]:
np.savetxt('test.txt', aa)


In [5]:
a = np.loadtxt("test.txt")
a[:10]

array([0., 0., 1., 1., 0.])

In [7]:
a_int = a.astype(int)
a_int[:3]

array([0, 0, 1])

In [9]:
np.savetxt('int_data.csv', a_int, delimiter=",")

In [12]:
np.save("npy_test", arr=a_int)

In [13]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

array([0, 0, 1])