# Lists

In [3]:
a = 'is'
b = 'nice'
my_list = ['my', 'list', a , b]
my_list2 = [[4,5,6,7], [3,4,5,6]]

## Selecting List Elements
### Subset

In [5]:
my_list[1] # Select item at index 1

'list'

In [6]:
my_list[-3] # Select 3rd last item

'list'

### Slice

In [7]:
my_list[1:3] # Select items at index 1 and 2

['list', 'is']

In [9]:
my_list[1:] # Select items after index 0

['list', 'is', 'nice']

In [10]:
my_list[:3] # Select items before index 3

['my', 'list', 'is']

In [11]:
my_list[:] # Copy my_list

['my', 'list', 'is', 'nice']

### Subset Lists of Lists

In [12]:
my_list2[1][0] # my_list[list][itemOfList]

3

In [13]:
my_list2[1][:2]

[3, 4]

## List Operations

In [14]:
my_list + my_list

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [15]:
my_list * 2

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

## List Methods

In [17]:
my_list.index(a) # Get the index of an item

2

In [18]:
my_list.count(a) # Count an item

1

In [19]:
my_list.append('!') # Append an item at a time
my_list

['my', 'list', 'is', 'nice', '!']

In [20]:
my_list.remove('!') # Remove an item
my_list

In [22]:
del(my_list[0:1]) # Remove an item
my_list

['list', 'is', 'nice']

In [25]:
my_list.reverse()
my_list

['nice', 'is', 'list']

In [26]:
my_list.extend("!") # Append an item
my_list

['nice', 'is', 'list', '!']

In [27]:
my_list.pop(-1) # Remove an item

'!'

In [28]:
my_list.insert(0,'!')
my_list

In [31]:
my_list.sort()
my_list

['!', 'is', 'list', 'nice']

# String

In [32]:
my_string = 'thisStringIsAwesome'
my_string

'thisStringIsAwesome'

## String Operations

In [33]:
my_string * 2

'thisStringIsAwesomethisStringIsAwesome'

In [34]:
my_string + 'Innit'

'thisStringIsAwesomeInnit'

In [36]:
'm' in my_string

True

In [37]:
my_string[3]

's'

In [38]:
my_string[4:9]

'Strin'

## String Methods

In [40]:
my_string.upper() # String to uppercase

'THISSTRINGISAWESOME'

In [41]:
my_string.lower() #String to lowercase

'thisstringisawesome'

In [42]:
my_string.count('w') #Count String elements

1

In [43]:
my_string.replace('e', 'i') #Replace String elements

'thisStringIsAwisomi'

In [44]:
my_string.strip() #Strip whitespaces

'thisStringIsAwesome'

# Libraries
## Import libraries

In [46]:
import numpy
import numpy as np

## Selective import

In [47]:
from math import pi

# Numpy Arrays

In [49]:
my_list = [1, 2, 3, 4]
my_list

[1, 2, 3, 4]

In [51]:
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [52]:
my_2darray = np.array([[1,2,3], [4,5,6]])
my_2darray

array([[1, 2, 3],
       [4, 5, 6]])

## Selecting Numpy Array Elements
### Subset

In [53]:
my_array[1]# Select item at index 1

2

### Slice

In [54]:
my_array[0:2] # Select items at index 0 and 1

array([1, 2])

### Subset 2D Numpy arrays

In [55]:
my_2darray[:,0] # my_2darray[rows, columns]

array([1, 4])

## Numpy Array Operations

In [56]:
my_array > 3

array([False, False, False,  True])

In [57]:
my_array * 2

array([2, 4, 6, 8])

In [58]:
my_array + np.array([5,6,7,8])

array([ 6,  8, 10, 12])

## Numpy Array Functions

In [60]:
my_array.shape # Get the dimensions of the array

(4,)

In [61]:
my_array2 = np.array(my_list)
my_array2

array([1, 2, 3, 4])

In [62]:
np.append(my_array, my_array2) # Append items to an array

array([1, 2, 3, 4, 1, 2, 3, 4])

In [65]:
np.insert(my_array, 1, 5) # Insert items in an array

array([1, 5, 2, 3, 4])

In [67]:
np.delete(my_array, [1]) # Delete items in an array(?2개 지워짐)

array([1, 3, 4])

In [68]:
np.mean(my_array) # Mean of the array

2.5

In [69]:
np.median(my_array) # Median of the array

2.5