# Creating Arrays

In [2]:
import numpy as np 
a = np.array([1,2,3])


In [3]:
b = np.array([(1.5,2,3),(4,5,6)], dtype=float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
c = np.array([ [(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],  dtype=float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

## Initial Placeholders

In [5]:
np.zeros((3,4)) # Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4), dtype=np.int16) # Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
d = np.arange(10,25,5) # Create an array of evenly spaced values (step value)
d

array([10, 15, 20])

In [8]:
np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
e = np.full((2,2),7) # Create a constant array
e

array([[7, 7],
       [7, 7]])

In [10]:
f = np.eye(2) # Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [11]:
np.random.random((2,2)) # Create an array with random values

array([[0.07901674, 0.17142793],
       [0.10713407, 0.45200393]])

In [12]:
np.empty((3,2)) # Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# I/O

## Saving & Loading On Disk

In [13]:
np.save('my_array', a)
np.savez('array.npz', a, b)

In [14]:
np.load('my_array.npy')

array([1, 2, 3])

## Saving & Loading Text Files

In [15]:
np.loadtxt("myfile.txt")

array([1., 2., 3.])

In [16]:
np.savetxt('myarray.txt', a, delimiter=" ")

## Data Types

In [17]:
np.int64 # Signed 64-bit integer types
np.float32 # Standard double-precision floating point
np.complex # Complex numbers represented by 128 floats
np.bool # Boolean type storing TRUE and FALSE values
np.object # Python object type
np.string_ # Fixed-length string type
np.unicode_ # Fixed-length unicode type

numpy.str_

# Inspecting Your Array

In [18]:
a.shape # Array dimensions

(3,)

In [19]:
len(a) # Length of array

3

In [20]:
b.ndim # Number of array dimensions

2

In [21]:
e.size # Number of array elements

4

In [22]:
b.dtype # Data type of array elements

dtype('float64')

In [23]:
b.dtype.name # Name of data type

'float64'

In [24]:
b.astype(int) #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

# Asking For Help

In [25]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Array Mathematics
## Arithmetic Operations

In [26]:
g = a - b # Subtraction
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [27]:
np.subtract(a,b) # Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [28]:
b + a #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [29]:
np.add(a,b) #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [30]:
a / b  #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [31]:
np.divide(a,b) #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [32]:
a * b #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [33]:
np.multiply(a,b) #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [34]:
np.exp(b) #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [35]:
np.sqrt(b) #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [36]:
np.sin(a) #Print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [37]:
np.cos(b) #Element-wise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [38]:
np.log(a) #Element-wise natural logarithm

array([0.        , 0.69314718, 1.09861229])

In [39]:
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

# Comparison

In [40]:
a == b #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [41]:
a < 2 #Element-wise comparison

array([ True, False, False])

In [42]:
np.array_equal(a, b) # Array-wise comparison

False

# Aggregate Functions

In [43]:
a

array([1, 2, 3])

In [44]:
a.sum() #Array-wise sum

6

In [45]:
a.min() #Array-wise minimum value

1

In [46]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [47]:
b.max(axis=0) #Maximum value of an array row

array([4., 5., 6.])

In [48]:
b.cumsum(axis=1) #Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [49]:
a.mean() #Mean

2.0

In [50]:
np.median(b) #Median

3.5

In [51]:
np.corrcoef(a) #Correlation coefficient

1.0

In [52]:
np.std(b) #Standard deviation

1.5920810978785667

# Copying Arrays

In [53]:
h = a.view() #Create a view of the array with the same data
h

array([1, 2, 3])

In [54]:
np.copy(a) #Create a copy of the array

array([1, 2, 3])

In [55]:
h = a.copy() #Create a deep copy of the array
h

array([1, 2, 3])

# Sorting Arrays

In [56]:
a.sort() #Sort an array
a

array([1, 2, 3])

In [57]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [58]:
c.shape

(2, 2, 3)

In [59]:
c.sort(axis=0) #Sort the elements of an array's axis

In [60]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

# Subsetting, Slicing, Indexing
## Subsetting

In [61]:
a

array([1, 2, 3])

In [62]:
a[2]#Select the element at the 2nd index

3

In [63]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [64]:
b[1,2] #Select the element at row 1 column 2 (equivalent to b[1][2])

6.0

## Slicing

In [65]:
a[0:2] #Select items at index 0 and 1

array([1, 2])

In [66]:
b[0:2,1] #Select items at rows 0 and 1 in column 1

array([2., 5.])

In [67]:
b[:1] # Select all items at row 0 (equivalent to b[0:1, :])

array([[1.5, 2. , 3. ]])

In [68]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [69]:
c[1,...] # Same as [1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [70]:
a[ : :-1] # Reversed array a

array([3, 2, 1])

## Boolean Indexing

In [71]:
a[a<2] # Select elements from a less than 2

array([1])

## Fancy Indexing

b

In [73]:
b[[1, 0, 1, 0],[0, 1, 2, 0]] # Select elements (1,0),(0,1),(1,2) and (0,0)

array([4. , 2. , 6. , 1.5])

In [74]:
b[[1, 0, 1, 0]][:,[0,1,2,0]] # Select a subset of the matrix’s rows and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

# Array Manipulation
## Transposing Array

In [77]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [75]:
i = np.transpose(b) # Permute array dimensions
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [78]:
i.T # Permute array dimensions

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Changing Array Shape

In [80]:
b.ravel() # Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [81]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [83]:
g.reshape(3,-2) #Reshape, but don’t change data

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

## Adding/Removing Elements

In [84]:
h

array([1, 2, 3])

In [87]:
np.resize(h,(2,6)) #Return a new array with shape (2,6)

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [89]:
np.append(h,g) # Append items to an array

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [90]:
np.insert(a,1,5) # Insert items in an array

array([1, 5, 2, 3])

In [91]:
np.delete(a,[1]) #Delete items from an array

array([1, 3])

## Combining Arrays

In [94]:
np.concatenate((a,d),axis=0) #Concatenate arrays

array([ 1,  2,  3, 10, 15, 20])

In [95]:
a,b

(array([1, 2, 3]), array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]))

In [96]:
np.vstack( (a,b) ) # Stack arrays vertically (row-wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [98]:
e, f 

(array([[7, 7],
        [7, 7]]), array([[1., 0.],
        [0., 1.]]))

In [99]:
np.r_[e,f] #Stack arrays vertically (row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [100]:
np.hstack((e,f)) # Stack arrays horizontally (column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [101]:
a,d

(array([1, 2, 3]), array([10, 15, 20]))

In [102]:
np.column_stack( (a,d) ) # Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [104]:
np.c_[a,d] # Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

## Splitting Arrays

In [106]:
np.hsplit(a,3) #Split the array horizontally at the 3rd index

[array([1]), array([2]), array([3])]

In [107]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [108]:
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]