# Creating Arrays

In [1]:
import numpy as np 
a = np.array([1,2,3])


In [2]:
b = np.array([(1.5,2,3),(4,5,6)], dtype=float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [3]:
c = np.array([ [(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],  dtype=float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

## Initial Placeholders

In [4]:
np.zeros((3,4)) # Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((2,3,4), dtype=np.int16) # Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [6]:
d = np.arange(10,25,5) # Create an array of evenly spaced values (step value)
d

array([10, 15, 20])

In [7]:
np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
e = np.full((2,2),7) # Create a constant array
e

array([[7, 7],
       [7, 7]])

In [9]:
f = np.eye(2) # Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [10]:
np.random.random((2,2)) # Create an array with random values

array([[0.42197964, 0.37603239],
       [0.99759723, 0.44548314]])

In [11]:
np.empty((3,2)) # Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# I/O

## Saving & Loading On Disk

In [12]:
np.save('my_array', a)
np.savez('array.npz', a, b)

In [13]:
np.load('my_array.npy')

array([1, 2, 3])

## Saving & Loading Text Files

In [14]:
np.loadtxt("myfile.txt")

array([1., 2., 3.])

In [15]:
np.savetxt('myarray.txt', a, delimiter=" ")

## Data Types

In [16]:
np.int64 # Signed 64-bit integer types
np.float32 # Standard double-precision floating point
np.complex # Complex numbers represented by 128 floats
np.bool # Boolean type storing TRUE and FALSE values
np.object # Python object type
np.string_ # Fixed-length string type
np.unicode_ # Fixed-length unicode type

numpy.str_

# Inspecting Your Array

In [17]:
a.shape # Array dimensions

(3,)

In [18]:
len(a) # Length of array

3

In [19]:
b.ndim # Number of array dimensions

2

In [20]:
e.size # Number of array elements

4

In [21]:
b.dtype # Data type of array elements

dtype('float64')

In [22]:
b.dtype.name # Name of data type

'float64'

In [23]:
b.astype(int) #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

# Asking For Help

In [24]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Array Mathematics
## Arithmetic Operations

In [25]:
g = a - b # Subtraction
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [26]:
np.subtract(a,b) # Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [27]:
b + a #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [28]:
np.add(a,b) #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [29]:
a / b  #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [30]:
np.divide(a,b) #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [31]:
a * b #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [32]:
np.multiply(a,b) #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [33]:
np.exp(b) #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [34]:
np.sqrt(b) #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [35]:
np.sin(a) #Print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [36]:
np.cos(b) #Element-wise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [37]:
np.log(a) #Element-wise natural logarithm

array([0.        , 0.69314718, 1.09861229])

In [38]:
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

# Comparison

In [39]:
a == b #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [40]:
a < 2 #Element-wise comparison

array([ True, False, False])

In [41]:
np.array_equal(a, b) # Array-wise comparison

False

# Aggregate Functions

In [42]:
a

array([1, 2, 3])

In [43]:
a.sum() #Array-wise sum

6

In [44]:
a.min() #Array-wise minimum value

1

In [45]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [46]:
b.max(axis=0) #Maximum value of an array row

array([4., 5., 6.])

In [47]:
b.cumsum(axis=1) #Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [49]:
a.mean() #Mean

2.0

In [53]:
np.median(b) #Median

3.5

In [54]:
np.corrcoef(a) #Correlation coefficient

1.0

In [55]:
np.std(b) #Standard deviation

1.5920810978785667